import{spawn}from"node:child_process";
import{readFileSync}from"node:fs";
import{request}from"node:http";
import{homedir}from"node:os";
import{join}from"node:path";
import{fileURLToPath}from"node:url";
export type DaemonEndpoint={host:string;port:number};
export type DaemonConnection={endpoint:DaemonEndpoint;adminToken:string};
function http(endpoint:DaemonEndpoint,token:string,path:string,method="GET"):Promise<any>{return new Promise((resolve,reject)=>{const req=request({host:endpoint.host==="0.0.0.0"?"127.0.0.1":endpoint.host,port:endpoint.port,path,method,headers:{authorization:`Bearer ${token}`}},res=>{let body="";res.on("data",x=>body+=x);res.on("end",()=>{if(!res.statusCode||res.statusCode>=300){reject(new Error(`daemon_${res.statusCode}`));return;}try{resolve(JSON.parse(body));}catch{resolve({});}});});req.setTimeout(2000,()=>req.destroy(new Error("daemon_timeout")));req.on("error",reject);req.end();});}
export function daemonRequest(endpoint:DaemonEndpoint,token:string,action:"status"|"stop"):Promise<any>{return http(endpoint,token,action==="stop"?"/admin/stop":"/health/ready",action==="stop"?"POST":"GET");}
export function daemonAdminRequest(connection:DaemonConnection,action:"pair"|"rotate"|"enable"|"disable",processId?:string,advertisedHost?:string):Promise<any>{const pairQuery=new URLSearchParams();if(processId)pairQuery.set("processId",processId);if(advertisedHost)pairQuery.set("advertisedHost",advertisedHost);const paths={pair:`/admin/v2-token${pairQuery.size?`?${pairQuery}`:""}`,rotate:"/admin/v2-rotate",enable:"/admin/enable",disable:"/admin/disable"}as const;return http(connection.endpoint,connection.adminToken,paths[action],"POST");}
export async function waitUntilReady(endpoint:DaemonEndpoint,token:string,timeoutMs=10000){const end=Date.now()+timeoutMs;let last:unknown;while(Date.now()<end){try{return await daemonRequest(endpoint,token,"status");}catch(e){last=e;await new Promise(r=>setTimeout(r,50));}}throw last??new Error("daemon_not_ready");}
export async function ensureDaemon(options:{profileRoot?:string;timeoutMs?:number}={}):Promise<DaemonConnection>{const root=options.profileRoot??process.env.PI_REMOTE_PROFILE??join(homedir(),".pi","agent","pi-remote");let config:any={};try{config=JSON.parse(readFileSync(join(root,"daemon.json"),"utf8"));}catch{}if(config.enabled===false)throw new Error("daemon_disabled");const endpoint={host:typeof config.host==="string"?config.host:"127.0.0.1",port:Number.isInteger(config.port)?config.port:37891};const credentials=()=>JSON.parse(readFileSync(join(root,"credentials.json"),"utf8")).adminToken as string;try{const adminToken=credentials();await waitUntilReady(endpoint,adminToken,300);return{endpoint,adminToken};}catch{}const cli=fileURLToPath(new URL("./cli.js",import.meta.url));const child=spawn(process.execPath,[cli,"run"],{detached:true,stdio:"ignore",env:{...process.env,PI_REMOTE_PROFILE:root}});child.unref();let adminToken="";for(let i=0;i<100&&!adminToken;i++){try{adminToken=credentials();}catch{await new Promise(r=>setTimeout(r,50));}}await waitUntilReady(endpoint,adminToken,options.timeoutMs??10000);return{endpoint,adminToken};}
