import{mkdirSync}from"node:fs";
import{join}from"node:path";
import{randomUUID}from"node:crypto";
import type WebSocket from"ws";
import{WebSocket as WsState}from"ws";
import{CommandRequestSchema,CommandResultSchema,EventPublishSchema,KNOWN_CAPABILITIES,ProtocolError,ProtocolSession,decodeTextFrame,parseCommandBody,parseEventBody,redactForLog,validateSchema}from"@nucleoid/pi-remote-protocol";
import{loadOrCreateCredentials,tokenVerifier}from"./credentials.js";
import{AuthService}from"./auth.js";
import{InstanceLock}from"./instance-lock.js";
import{DurableStore}from"./store.js";
import{createControlServer}from"./http-server.js";
import{ProcessRegistry,SocketBinding}from"./process-registry.js";
import{CommandRouter}from"./command-router.js";
import{ReplaySubscription}from"./subscriptions.js";
import{BoundedQueue}from"./backpressure.js";
import{V2SessionManager}from"./v2-session.js";

type Options={profileRoot:string;host:string;port:number;legacyToken?:string;allowNoAuthFromLoopback?:boolean;maxEvents?:number;maxAgeDays?:number;maxInboundItems?:number;maxOutboundItems?:number};
type Committed=Record<string,any>&{cursor:number};
class Sender{#queue:BoundedQueue<string>;#scheduled=false;constructor(private ws:WebSocket,maxItems:number){this.#queue=new BoundedQueue(maxItems,8*1024*1024,x=>Buffer.byteLength(x));}send(value:unknown){try{this.#queue.push(JSON.stringify(value));this.flush();}catch{this.ws.close(1013,"backpressure");}}flush(){if(this.#scheduled)return;this.#scheduled=true;setImmediate(()=>{this.#scheduled=false;while(this.ws.readyState===WsState.OPEN){if(this.ws.bufferedAmount>4*1024*1024){this.ws.close(1013,"backpressure");return;}const value=this.#queue.shift();if(value===undefined)return;this.ws.send(value);}});}}
class ControlPlane{
  readonly registry:ProcessRegistry;readonly router:CommandRouter;readonly v2:V2SessionManager;#subscriptions=new Set<{sub:ReplaySubscription<Committed>;processIds?:Set<string>;lease:string}>();
  constructor(private store:DurableStore,private maxInboundItems=64,private maxOutboundItems=256){this.router=new CommandRouter(store);this.v2=new V2SessionManager(x=>store.getV2Assignment(x),(x,p)=>store.saveV2Assignment(x,p));this.registry=new ProcessRegistry(()=>performance.now(),(id,state)=>{store.setInstanceState(id,state);const process=(store.db.prepare("SELECT process_id FROM process_instances WHERE instance_id=?").get(id) as any)?.process_id;if(process)this.v2.setLive(process,state==="live");});for(const p of store.listProcesses())this.v2.register(p);}
  accept(ws:WebSocket){const session=new ProtocolSession([3],KNOWN_CAPABILITIES),sender=new Sender(ws,this.maxOutboundItems);let binding:SocketBinding|undefined,subscriber:{sub:ReplaySubscription<Committed>;processIds?:Set<string>;lease:string}|undefined,pending=0,chain=Promise.resolve();
    ws.on("message",(data,binary)=>{const bytes=typeof data==="string"?Buffer.byteLength(data):data instanceof Buffer?data.length:Buffer.byteLength(String(data));if(++pending>this.maxInboundItems){ws.close(1013,"backpressure");return;}chain=chain.then(()=>this.message(decodeTextFrame(data as any,binary),session,sender,()=>binding,x=>binding=x,x=>subscriber=x,()=>ws.close(1013,"backpressure"))).catch(error=>this.protocolError(ws,sender,error)).finally(()=>pending--);if(bytes>32*1024*1024)ws.close(1009,"frame too large");});
    ws.on("close",()=>{if(subscriber){this.#subscriptions.delete(subscriber);this.store.releaseReplay(subscriber.lease);}if(binding){this.router.disconnect(binding.processId,binding.processInstanceId);this.store.setInstanceState(binding.processInstanceId,"dead");this.v2.setLive(binding.processId,false);}});
  }
  async message(value:any,session:ProtocolSession,sender:Sender,getBinding:()=>SocketBinding|undefined,setBinding:(x:SocketBinding)=>void,setSubscriber:(x:{sub:ReplaySubscription<Committed>;processIds?:Set<string>;lease:string})=>void,closeBackpressure:()=>void){const reply=session.receive(value);if(reply){sender.send(reply);return;}const binding=getBinding();
    if(value.type==="process.register"){if(session.role!=="bridge"||binding)throw new ProtocolError("role_violation");const registered=this.store.register({...value,capabilities:value.capabilities});const next=new SocketBinding(value.processId,value.processInstanceId);setBinding(next);this.registry.register(value.processInstanceId,value.heartbeatIntervalMs);this.v2.register({processId:value.processId,registeredAt:Date.now(),live:true});this.router.bind(value.processId,value.processInstanceId,x=>sender.send(x),()=>this.registry.canRoute(value.processInstanceId));sender.send({protocolVersion:3,type:"process.registered",processId:value.processId,processInstanceId:value.processInstanceId,...registered});return;}
    if(value.type==="heartbeat"){if(!binding)throw new ProtocolError("producer_not_registered");binding.assertProducer(value);this.registry.heartbeat(binding.processInstanceId);this.store.heartbeat(binding.processInstanceId);return;}
    if(value.type==="event.publish"){if(session.role!=="bridge"||!binding)throw new ProtocolError("producer_not_registered");validateSchema(EventPublishSchema,value,"invalid_event_publish");parseEventBody(value.event);binding.assertProducer(value);const committed=this.store.appendEvent(value);sender.send({protocolVersion:3,type:"event.ack",eventId:value.eventId,cursor:committed.cursor,expectedNextProcessSequence:committed.expectedNextSequence,duplicate:committed.duplicate});if(!committed.duplicate)this.publish({...value,cursor:committed.cursor});return;}
    if(value.type==="events.subscribe"){if(session.role!=="client")throw new ProtocolError("role_violation");const processIds=value.processIds?.length?new Set<string>(value.processIds):undefined,head=this.store.headCursor,lease=this.store.leaseReplay(value.afterCursor+1,60000),sub=new ReplaySubscription<Committed>(this.maxOutboundItems,closeBackpressure),entry={sub,processIds,lease};this.#subscriptions.add(entry);setSubscriber(entry);await sub.start(value.afterCursor,head,async after=>this.store.replay(after,processIds?[...processIds]:undefined).filter(x=>x.cursor<=head) as Committed[],item=>sender.send(this.wireEvent(item)));return;}
    if(value.type==="command.request"){if(session.role!=="client")throw new ProtocolError("role_violation");validateSchema(CommandRequestSchema,value,"invalid_command_request");const command=parseCommandBody(value.command);if(command.type==="unknown")throw new ProtocolError("unsupported_command");const target=this.store.getProcess(value.targetProcessId);if(!target?.processInstanceId||target.state!=="live"||!this.registry.canRoute(target.processInstanceId))throw new ProtocolError("target_unavailable",undefined,"Target unavailable",1008);if(value.sessionId&&value.sessionId!==target.sessionId)throw new ProtocolError("session_generation_conflict");const expiresAt=value.deadline?Date.parse(value.deadline):undefined;if(expiresAt!==undefined&&!Number.isFinite(expiresAt))throw new ProtocolError("invalid_command_request");const result=this.router.accept("admin",{commandId:value.commandId,processId:value.targetProcessId,processInstanceId:target.processInstanceId,payload:command,expiresAt},x=>sender.send(x));sender.send({protocolVersion:3,type:"command.ack",commandId:value.commandId,status:"accepted",...(result.duplicate?{duplicate:true}:{})});return;}
    if(value.type==="command.result"){if(session.role!=="bridge"||!binding)throw new ProtocolError("role_violation");validateSchema(CommandResultSchema,value,"invalid_command_result");this.router.complete(binding.processId,binding.processInstanceId,value);return;}
    throw new ProtocolError("unsupported_message");
  }
  publish(value:Committed){for(const x of this.#subscriptions)if(!x.processIds||x.processIds.has(value.processId))try{x.sub.buffer(value);}catch{x.sub;}}
  wireEvent(x:Committed){return{protocolVersion:3,type:"event.committed",cursor:x.cursor,eventId:x.eventId,processId:x.processId,processInstanceId:x.processInstanceId,processSequence:x.processSequence,occurredAt:x.occurredAt,event:x.event};}
  routeV2(processId:string,value:any){const target=this.store.getProcess(processId);if(!target?.processInstanceId)throw new Error("target_unavailable");this.router.accept("v2",{commandId:typeof value.id==="string"&&/^[0-9a-f-]{36}$/i.test(value.id)?value.id:randomUUID(),processId,processInstanceId:target.processInstanceId,payload:value.command});}
  protocolError(ws:WebSocket,sender:Sender,error:unknown){const safe=redactForLog(error) as any;sender.send({protocolVersion:3,type:"protocol_error",code:safe.code??"invalid_message",message:"Protocol error",...(safe.details?.minimumCursor?{minimumCursor:safe.details.minimumCursor}:{})});ws.close(error instanceof ProtocolError?error.closeCode:1002,"protocol error");}
  sweep(){this.registry.sweep();}
}
export class LocalDaemon{#lock?:InstanceLock;#store?:DurableStore;#server?:ReturnType<typeof createControlServer>;#timer?:NodeJS.Timeout;#resolveClosed!:()=>void;#stopping=false;readonly closed:Promise<void>;adminToken="";endpoint:{host:string;port:number};constructor(readonly options:Options){this.endpoint={host:options.host,port:options.port};this.closed=new Promise(r=>this.#resolveClosed=r);}async start(){mkdirSync(this.options.profileRoot,{recursive:true});const credentials=loadOrCreateCredentials(join(this.options.profileRoot,"credentials.json"));this.adminToken=credentials.adminToken;const birth=`${process.pid}:${Date.now()-Math.floor(process.uptime()*1000)}`;this.#lock=InstanceLock.acquire(join(this.options.profileRoot,"daemon.lock"),{pid:process.pid,birth,port:this.options.port,version:"0.1.0",isExactOwnerAlive:owner=>{if(owner.pid===process.pid)return owner.birth===birth;try{process.kill(owner.pid,0);return undefined;}catch(e:any){return e.code==="ESRCH"?false:undefined;}}});try{this.#store=new DurableStore(join(this.options.profileRoot,"control.db"));this.#store.recoverAfterRestart();const auth=new AuthService();auth.add(this.adminToken,"admin");if(this.options.legacyToken)auth.add(this.options.legacyToken,"v2");const control=new ControlPlane(this.#store,this.options.maxInboundItems,this.options.maxOutboundItems);this.#server=createControlServer({auth,host:this.options.host,port:this.options.port,headCursor:()=>this.#store!.headCursor,minimumCursor:()=>this.#store!.minimumCursor,onStop:()=>void this.stop(),allowNoAuthFromLoopback:this.options.allowNoAuthFromLoopback,control,v2:{manager:control.v2,history:processId=>this.#store!.replay(Math.max(0,this.#store!.minimumCursor-1),[processId]).map(x=>x.event),command:(processId,value)=>control.routeV2(processId,value),verifier:token=>tokenVerifier(credentials.key,token??"loopback")}});await this.#server.listen();this.endpoint={host:this.options.host,port:this.#server.port};this.#timer=setInterval(()=>{control.sweep();this.#store?.retain({maxEvents:this.options.maxEvents??1_000_000,maxAgeMs:(this.options.maxAgeDays??30)*86400000,now:Date.now()});},10000);this.#timer.unref();return this;}catch(e){await this.stop();throw e;}}async stop(){if(this.#stopping)return this.closed;this.#stopping=true;if(this.#timer)clearInterval(this.#timer);try{await this.#server?.close();}catch{}try{this.#store?.checkpoint();this.#store?.close();}catch{}this.#lock?.release(this.#lock.nonce);this.#resolveClosed();}}
